### PR TITLE
Updated SSLv3 to TLSv1.2

### PR DESCRIPTION
**Pull request by Sebbo94BY**
Updated protocol for encrypted ServerQuery connections (Related to #78)

### CODE REVIEW

**Comment by ronindesign** [comment]
Yep, this looks right / makes sense. I'll pull, test and merge it today.

I've typically seen
`STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT` + `STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT`

So your fix should do it, thanks for the pull request!

**Comment by svenpaulsen** [comment]
This was a quick fix to support SSL/TLS in TeaSpeak. As soon as the official TeamSpeak Server supports encrypted ServerQuery connections, we'll update the code with the appropriate protocols.

**Comment by DatDraggy** [comment]
ETA on the SSH version of this?

**Comment by ronindesign** [comment]
@DatDraggy There is no ETA... as Sven said, we can't implement this until it is supported by TeamSpeak Server:
> As soon as the official TeamSpeak Server supports encrypted ServerQuery connections, we'll update the code with the appropriate protocols.

**Comment by DatDraggy** [comment]
Oh sorry I looked at the beta release. The beta offers SSH now.

**Comment by ronindesign** [comment]
Ah, sorry for the confusion then. Yeah, once they release to stable we will follow with support.

**Pull request closed without merging**
