### PR TITLE
Update some Annotation

### PR DESCRIPTION
**Pull request by thhan**
Is helpful in working with IDE

### CODE REVIEW

**Comment by ronindesign** [comment]
@thhan Thanks for the PR, really appreciate the contribution.

As @jens1o mentions, there's a little bit of formatting clean-up that needs to be done.

We'll definitely merge in once it's ready. Thanks again!

**Comment by jens1o** [comment]
@ronindesign Please file a new release immediately after merging this one 😅

**Comment by ronindesign** [comment]
@jens1o not sure if sarcasm in your last comment haha, but I've tagged this as `pre-release 1.1.27` just incase... 😅

**Comment by jens1o** [comment]
Awesome. That wasn't that much sarcasm, but I'm to lazy and I don't want to be on dev-master. ;)

**Comment by thhan** [comment]
That is, why I start this merge request :smile:

**Pull request merged**
