### PR TITLE
Refactor to PHP 8 standards

### PR DESCRIPTION
**Pull request by je-schindler**
Solve #151, solve #165, add return and parameter types, fix type consistency.

### CODE REVIEW

**Comment by ronindesign** [comment]
Thank you for taking the time to refactor and contribute this PR, really appreciate it!

Please give me a day or so to review before we merge in.

**Comment by je-schindler** [comment]
No worries, take your time. Let me know then if you wish for a change or if you found a bug. :D

**Comment by Sebi94nbg** [comment]
Sooo many changes. <3 :D

Will it also already support PHP 8.2 then?

@ronindesign what's the status of your review? PHP 7.4 is dead since a while.

**Comment by ronindesign** [comment]
My apologies for the delay on following up on this and thank you for the ping, it had fallen off my Radar. What I've reviewed so far looks fantastic. I'll finish reviewing this evening (PST) and merge if no issues. Thanks for all your work on this, really appreciate it!

**Comment by je-schindler** [comment]
You're welcome. But I'd be happy if you could test anything again, as I found (and fixed) some issues, but cannot guarantee I missed something.

**Comment by Sebi94nbg** [comment]
From my side, the changes look good. But I may have overseen something as there are a lot of changes. :sweat_smile:

Can I somehow support you with the tests, @ronindesign ?

By the way: Some Github workflows with automated tests would be great. I'll take a look at this later.

**Comment by ronindesign** [comment]
Alright, this all looks great to me. I'm merging now to `dev`. @Sebi94nbg I see #167, that would be a great help to catch any issues or regressions in the future. Additionally, simply using the `dev` branch live would help a lot to make sure no runtime/logic issues.

**Comment by Sebi94nbg** [comment]
@ronindesign now you can choose, which one you want to review and merge :D

- DEV: https://github.com/planetteamspeak/ts3phpframework/pull/168
- MASTER: https://github.com/planetteamspeak/ts3phpframework/pull/167

**Pull request merged**
