### PR TITLE
Initial / current code commit - v1.1.23

### PR DESCRIPTION
**Pull request by ronindesign**
Initial code commit of TS3 PHP Framework in two pieces:
1) All files (v1.1.23) directly from planetteamspeak.com/downloads
2) Additionally (v1.1.18) files which include "examples" folder. Source:
github.com/Luceos/ts3-php
"examples" folder has been copied to main / top directory simply for
visibility.

### CODE REVIEW

**Comment by Bluscream** [comment]
bump

**Comment by ronindesign** [comment]
Yeah, would be nice if we could get this PR pulled up into master so future people can fork directly from there instead of my downstream branch...

**Comment by svenpaulsen** [comment]
I've added the latest framework files (version 1.x) to this repository. The examples, however, are obsolete. I'd prefer having examples in the documentation.

**Comment by ronindesign** [comment]
Thanks for the update and the new subversion (*.24)! I'll fork off this, create some new examples, and maybe an updated version of the docs based off of code base 1.1.24 (for offline use).

Thanks again for the work on this, still using heavily years later!

**Pull request closed without merging**
