### PR TITLE
Create some tests and configure travis for CI

### PR DESCRIPTION
**Pull request by thhan**

### CODE REVIEW

**Comment by ronindesign** [comment]
Thanks for the PR @thhan! I'll review asap.

If any one else wants to give this a once over,  it would help out!

**Comment by ronindesign** [comment]
@thhan still reviewing this, looking great so far!

Would you mind updating the contribution guidelines with details on environment requirements, how to, and examples for testing?

I've created [CONTRIBUTING.md](https://github.com/planetteamspeak/ts3phpframework/blob/master/CONTRIBUTING.md) in master, you'll need to pull and merge downstream into your fork.

Thanks again, it will be great to get some official testing coverage, especially when it comes to tracking down bugs the TeamSpeak developers might introduce down the road!

**Comment by thhan** [comment]
You have to add Travis in this repository. Travis will Test each pull-request and you can see directly, of something failed.

**Comment by ronindesign** [comment]
@thhan I realize that for the CI, but I'm just referring to testing locally with PHPUnit, before someone creates a PR, etc. CI on GitHub is really the last step just to make sure nothing was missed.

**Comment by thhan** [comment]
Don't forget to activate travis ;-)

**Comment by ronindesign** [comment]
@thhan I don't have access to Travis on this repo. Maybe @svenpaulsen can activate it.

**Pull request merged**
