### PR TITLE
Update dependencies and require php 8.0 or higher

### PR DESCRIPTION
**Pull request by nick-strohm**
As PHP 5.6 reached its EOL almost 3,5 years ago (s. [PHP: Unsupported Branches](https://www.php.net/eol.php)) and is not receiving any security update since, it is highly advised to upgrade to a [current version](https://www.php.net/supported-versions.php). I chose PHP 8.0 as a new base, because it is currently and for the next one and a half years actively supported and does not only receive security support for the next 5 months like PHP 7.4.

Also I fixed the tests where the method `assertInternalType` was being used as it is not supported and available anymore. I replaced it with following corresponding methods: `assertIsString`, `assertIsInt`, etc.

### CODE REVIEW

**Comment by sutcliffe121** [comment]
Just upgrading my site to laravel 9/PHP 8  and came across a compatibility problem with this package. It would be great if this  PR was merged and a new release created.

**Comment by nick-strohm** [comment]
@sutcliffe121 thanks for your reply. You can still use the PR as is, when you directly reference it from GitHub. Be advised that it can be a security concern. See how I required my fork inside my laravel library https://github.com/nick-strohm/laravel-ts3-php-framework/blob/dev/composer.json

**Comment by sutcliffe121** [comment]
Thanks @nick-strohm I will try that for now.

**Review by ronindesign — APPROVED** [review]
Looks good! Thank you for your time and effort in making these changes.

**Pull request merged**
